=== Dimitrije1997/kolokvijum1/magacin.dtd
<!ELEMENT Magacin (artikal)+>

<!ELEMENT artikal (naziv,datum_izrade,cena,kompanija_prodavca,(email_prodavca)+)>

<!ELEMENT naziv (#PCDATA)>
<!ATTLIST naziv sifra ID #REQUIRED>


<!ELEMENT datum_izrade (dan,mesec,godina)>
<!ELEMENT dan (#PCDATA)>
<!ELEMENT mesec (#PCDATA)>
<!ELEMENT godina (#PCDATA)>


<!ELEMENT cena (#PCDATA)>
<!ATTLIST cena valuta (dinar|euro) "dinar">

<!ELEMENT kompanija_prodavca (ime_kompanije,(adresa)+)>
<!ELEMENT ime_kompanije (#PCDATA)>
<!ELEMENT adresa (#PCDATA)>

<!ELEMENT email_prodavca (#PCDATA)>
<!ATTLIST email_prodavca tip (privatni|sluzbeni) #REQUIRED>

=== Dimitrije1997/kolokvijum1/magacin.xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<!DOCTYPE Magacin SYSTEM "magacin.dtd">

<Magacin xmlns="http://www.w3schools.com"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.w3schools.com magacin.xsd">

    <artikal>

        <naziv sifra="25">Naziv1</naziv>
        <datum_izrade>
            <dan>8</dan>
            <mesec>12</mesec>
            <godina>2019</godina>
        </datum_izrade>

        <cena valuta="dinar">1000</cena>
        <kompanija_prodavca>
            <ime_kompanije>Kompanija1</ime_kompanije>
            <adresa>Adresa1</adresa>
        </kompanija_prodavca>

        <email_prodavca tip="privatni">E1mail@gmail.com</email_prodavca>
        <email_prodavca tip="sluzbeni">E2mailadresa@gmail.com</email_prodavca>

    </artikal>

    <artikal>

        <naziv sifra="12">Naziv2</naziv>
        <datum_izrade>
            <dan>9</dan>
            <mesec>11</mesec>
            <godina>2018</godina>
        </datum_izrade>

        <cena valuta="euro">20</cena>
        <kompanija_prodavca>
            <ime_kompanije>Kompanija2</ime_kompanije>
            <adresa>Adresa2</adresa>
            <adresa>Adresa3</adresa>
        </kompanija_prodavca>

        <email_prodavca tip="sluzbeni">N3ekiEmail@gmail.com</email_prodavca>
        
    </artikal>

</Magacin>
